version: '3'

services:
    rru:
        build: ./rru/
        image: rru
        privileged: true
        network_mode: host
        stdin_open: true
        tty: true
        volumes:
            - "./config_files/:/config_files"
            - "/dev/bus/usb:/dev/bus/usb"

    rru-ue:
        build: ./rru-ue/
        image: rru-ue
        privileged: true
        network_mode: host
        stdin_open: true
        tty: true
        volumes:
            - "./config_files/:/config_files"
            - "/dev/bus/usb:/dev/bus/usb"

    rcc:
        build: ./rcc/
        image: rcc
        privileged: true
        network_mode: host
        stdin_open: true
        tty: true
        volumes:
            - "./config_files/:/config_files"
            - "/dev/bus/usb:/dev/bus/usb"
